### ISSUE TITLE
Status is reversed

### ISSUE THREAD

**Issue by JoopIdema** [lokonli/slide-domoticz#18]
Since updating to Domoticz version 2022.2 en slide-domoticz 1.01, the open and close status are reversed. The percentage bar is correct. I allready removed and re-added the slide but that did not fix it. Nor stopping and starting domoticz.
I also tried removing the plugin from the plugins folder and instaling it again.

Is there a way to fix this?

**Comment by lokonli** [comment]
Did you already try latest version?
A fix was made 2 months ago.

**Comment by JoopIdema** [comment]
Yes, I installed the latest version.

________________________________
Van: Lokonli ***@***.***>
Verzonden: Wednesday, December 14, 2022 9:05:45 PM
Aan: lokonli/slide-domoticz ***@***.***>
CC: JoopIdema ***@***.***>; Author ***@***.***>
Onderwerp: Re: [lokonli/slide-domoticz] Status is reversed (Issue #18)


Did you already try latest version?
A fix was made 2 months ago.

**Comment by lokonli** [comment]
Indeed, the Domoticz version is detected incorrectly by the plugin.
I'll make a fix.
In the mean time, if you tick the 'Reverse Open/Close state' in the settings of your slide device it should work.

**Comment by lokonli** [comment]
Should be fixed with version 1.0.2. @JoopIdema Can you test?

**Comment by JoopIdema** [comment]
Still not ok. 
The status is ok now, but the percentage bar is reversed.

**Comment by lokonli** [comment]
In Domoticz 100% means open, 0% closed.
With 100% the slider should be on the right and the curtains open.

Also see:
https://www.domoticz.com/wiki/Blinds


What do you mean with the percentage bar is reversed?

(The Innovation in Motion Slider app works the other way around: slider right means curtain closed)

**Comment by JoopIdema** [comment]
I did not know that, what is written in that Wiki. I thought it was the other way around. 
So I thought 100% meant closed and 0% meant open.  That is why I wrote, it is ''reversed'. 

So problem solved. Thanks!

**Comment by lokonli** [comment]
ok. I'll close this issue.
